DATECODE:=$(shell date -u "+%Y%m%d")
SHELL=/bin/bash

T_LIVE_ARCHS=i686 x86_64{,-musl} aarch64{,-musl} asahi{,-musl}

T_PLATFORMS=rpi-{armv{6,7}l,aarch64}{,-musl} GCP{,-musl} pinebookpro{,-musl} asahi{,-musl}
T_ARCHS=i686 x86_64{,-musl} armv{6,7}l{,-musl} aarch64{,-musl}

T_SBC_IMGS=rpi-{armv{6,7}l,aarch64}{,-musl} pinebookpro{,-musl}
T_CLOUD_IMGS=GCP{,-musl}

T_PXE_ARCHS=x86_64{,-musl}

T_WSL_ARCHS={x86_64,aarch64}{,-musl}

LIVE_ARCHS:=$(shell echo $(T_LIVE_ARCHS))
LIVE_FLAVORS:=base server xfce xfce-wayland kde bspwm river
LIVE_PLATFORMS:=pinebookpro x13s
ARCHS:=$(shell echo $(T_ARCHS))
PLATFORMS:=$(shell echo $(T_PLATFORMS))
SBC_IMGS:=$(shell echo $(T_SBC_IMGS))
CLOUD_IMGS:=$(shell echo $(T_CLOUD_IMGS))
PXE_ARCHS:=$(shell echo $(T_PXE_ARCHS))
WSL_ARCHS:=$(shell echo $(T_WSL_ARCHS))

ALL_LIVE_ISO=$(foreach arch,$(LIVE_ARCHS), $(foreach flavor,$(LIVE_FLAVORS),void-live-$(arch)-$(DATECODE)-$(flavor).iso))
ALL_ROOTFS=$(foreach arch,$(ARCHS),void-$(arch)-ROOTFS-$(DATECODE).tar.xz)
ALL_PLATFORMFS=$(foreach platform,$(PLATFORMS),void-$(platform)-PLATFORMFS-$(DATECODE).tar.xz)
ALL_SBC_IMAGES=$(foreach platform,$(SBC_IMGS),void-$(platform)-$(DATECODE).img.xz)
ALL_CLOUD_IMAGES=$(foreach cloud,$(CLOUD_IMGS),void-$(cloud)-$(DATECODE).tar.gz)
ALL_PXE_ARCHS=$(foreach arch,$(PXE_ARCHS),void-$(arch)-NETBOOT-$(DATECODE).tar.gz)
ALL_WSL=$(foreach arch,$(WSL_ARCHS),void-$(arch)-$(DATECODE).wsl)

SUDO := sudo

REPOSITORY := https://repo-fi.voidlinux.org/current
XBPS_REPOSITORY := -r $(REPOSITORY) -r $(REPOSITORY)/musl -r $(REPOSITORY)/aarch64
COMPRESSOR_THREADS:=$(shell nproc)

all:

README.md: README.md.in t4n-iso.sh t4n-live.sh t4n-rootfs.sh t4n-platformfs.sh t4n-image.sh t4n-net.sh
	printf '<!-- DO NOT EDIT, generated by make README.md -->\n\n' > README.md
	cat README.md.in >> README.md
	for script in t4n-iso t4n-live t4n-rootfs t4n-platformfs t4n-image t4n-net; do \
		printf '### %s.sh\n\n```\n' "$${script}" >> README.md ; \
		"./$${script}.sh" -h 2>/dev/null >> README.md ; \
		printf '```\n\n' >> README.md ; \
	done

t4n-iso.sh: t4n-live.sh

checksum: distdir-$(DATECODE)
	cd distdir-$(DATECODE)/ && sha256 * > sha256sum.txt

distdir-$(DATECODE):
	mkdir -p distdir-$(DATECODE)

dist: distdir-$(DATECODE)
	mv t4n*$(DATECODE)* distdir-$(DATECODE)/

live-iso-all: $(ALL_LIVE_ISO)

live-iso-all-print:
	@echo $(ALL_LIVE_ISO) | sed "s: :\n:g"

t4n-live-%.iso: t4n-iso.sh
	@[ -n "${CI}" ] && printf "::group::\x1b[32mBuilding $@...\x1b[0m\n" || true
	$(if $(findstring aarch64,$*), \
		$(SUDO) ./t4n-iso.sh -r $(REPOSITORY) -t $* -- -P "$(LIVE_PLATFORMS)", \
		$(SUDO) ./t4n-iso.sh -r $(REPOSITORY) -t $*)
	@[ -n "${CI}" ] && printf '::endgroup::\n' || true

rootfs-all: $(ALL_ROOTFS)

rootfs-all-print:
	@echo $(ALL_ROOTFS) | sed "s: :\n:g"

t4n_os-%-ROOTFS-$(DATECODE).tar.xz: t4n-rootfs.sh
	@[ -n "${CI}" ] && printf "::group::\x1b[32mBuilding $@...\x1b[0m\n" || true
	$(SUDO) ./t4n-rootfs.sh $(XBPS_REPOSITORY) -x $(COMPRESSOR_THREADS) -o $@ $*
	@[ -n "${CI}" ] && printf '::endgroup::\n' || true

platformfs-all: $(ALL_PLATFORMFS)

platformfs-all-print:
	@echo $(ALL_PLATFORMFS) | sed "s: :\n:g"

.SECONDEXPANSION:
t4n_os-%-PLATFORMFS-$(DATECODE).tar.xz: t4n_os-$$(shell ./lib.sh platform2arch %)-ROOTFS-$(DATECODE).tar.xz t4n-platformfs.sh
	@[ -n "${CI}" ] && printf "::group::\x1b[32mBuilding $@...\x1b[0m\n" || true
	$(SUDO) ./t4n-platformfs.sh $(XBPS_REPOSITORY) -x $(COMPRESSOR_THREADS) -o $@ $* t4n_os-$(shell ./lib.sh platform2arch $*)-ROOTFS-$(DATECODE).tar.xz
	@[ -n "${CI}" ] && printf '::endgroup::\n' || true

images-all: platformfs-all images-all-sbc images-all-cloud

images-all-sbc: $(ALL_SBC_IMAGES)

images-all-sbc-print:
	@echo $(ALL_SBC_IMAGES) | sed "s: :\n:g"

images-all-cloud: $(ALL_CLOUD_IMAGES)

images-all-print:
	@echo $(ALL_SBC_IMAGES) $(ALL_CLOUD_IMAGES) | sed "s: :\n:g"

t4n_os-%-$(DATECODE).img.xz: t4n_os-%-PLATFORMFS-$(DATECODE).tar.xz t4n-image.sh
	@[ -n "${CI}" ] && printf "::group::\x1b[32mBuilding $@...\x1b[0m\n" || true
	$(SUDO) ./t4n-image.sh -x $(COMPRESSOR_THREADS) -o $(basename $@) t4n_os-$*-PLATFORMFS-$(DATECODE).tar.xz
	@[ -n "${CI}" ] && printf '::endgroup::\n' || true

# Some of the images MUST be compressed with gzip rather than xz, this
# rule services those images.
t4n_os-%-$(DATECODE).tar.gz: t4n_os-%-PLATFORMFS-$(DATECODE).tar.xz t4n-image.sh
	@[ -n "${CI}" ] && printf "::group::\x1b[32mBuilding $@...\x1b[0m\n" || true
	$(SUDO) ./t4n-image.sh -x $(COMPRESSOR_THREADS) t4n_os-$*-PLATFORMFS-$(DATECODE).tar.xz
	@[ -n "${CI}" ] && printf '::endgroup::\n' || true

pxe-all: $(ALL_PXE_ARCHS)

pxe-all-print:
	@echo $(ALL_PXE_ARCHS) | sed "s: :\n:g"

t4n_os-%-NETBOOT-$(DATECODE).tar.gz: t4n_os-%-ROOTFS-$(DATECODE).tar.xz t4n-net.sh
	@[ -n "${CI}" ] && printf "::group::\x1b[32mBuilding $@...\x1b[0m\n" || true
	$(SUDO) ./t4n-net.sh t4n_os-$*-ROOTFS-$(DATECODE).tar.xz
	@[ -n "${CI}" ] && printf '::endgroup::\n' || true

wsl-all: $(ALL_WSL)

wsl-all-print:
	@echo $(ALL_WSL) | sed "s: :\n:g"

t4n_os-%-$(DATECODE).wsl: t4n-rootfs.sh
	@[ -n "${CI}" ] && printf "::group::\x1b[32mBuilding $@...\x1b[0m\n" || true
	$(SUDO) ./t4n-rootfs.sh $(XBPS_REPOSITORY) -x $(COMPRESSOR_THREADS) -b wsl-base -o $@ $*
	@[ -n "${CI}" ] && printf '::endgroup::\n' || true

.PHONY: all checksum dist live-iso-all live-iso-all-print rootfs-all-print rootfs-all platformfs-all-print platformfs-all pxe-all-print pxe-all wsl-all-print wsl-all
