#!/bin/sh

#  ╔╗ ╔═╗╔═╗╦ ╦╔╦╗  ╔═╗╔═╗╔╗╔╔═╗╦╔═╗  ╦ ╦╔═╗╦═╗╦╔═╔═╗╔═╗╔═╗╔═╗╔═╗╔═╗
#  ╠╩╗╚═╗╠═╝║║║║║║  ║  ║ ║║║║╠╣ ║║ ╦  ║║║║ ║╠╦╝╠╩╗╚═╗╠═╝╠═╣║  ║╣ ╚═╗
#  ╚═╝╚═╝╩  ╚╩╝╩ ╩  ╚═╝╚═╝╝╚╝╚  ╩╚═╝  ╚╩╝╚═╝╩╚═╩ ╩╚═╝╩  ╩ ╩╚═╝╚═╝╚═╝

# Autostart
~/.config/bspwm/0A &

# Lockscreen
xss-lock -- ~/.config/bspwm/scripts/auto-lock &
xautolock -time 5 -locker "pkill -USR1 xss-lock" -detectsleep -corners ---- &

# Desktop
bspc monitor -d 1 2 3 4 5 6

# Border settings
bspc config border_width            2
bspc config window_gap              10
bspc config split_ratio             0.50
bspc config focus_follows_pointer   true

# Layout
bspc config single_monocle        false
bspc config borderless_monocle    true
bspc config gapless_monocle       true

# Colors
bspc config normal_border_color  "#3c3836"
bspc config active_border_color  "#458588"
bspc config focused_border_color "#689d6a"
