#!/usr/bin/env bash

# Sesuaikan dengan card kamu, biasanya "alsa_card.pci-0000_00_1f.3"
CARD=$(pactl list cards short | awk '{print $1}' | head -n1)

CURRENT=$(pactl list cards | grep "Active Profile" | awk '{print $3}')

if [[ "$CURRENT" == output:hdmi* ]]; then
    pactl set-card-profile $CARD output:analog-stereo
    notify-send "🔊 Audio Switch" "Audio Switch to Main Display"
else
    pactl set-card-profile $CARD output:hdmi-stereo
   notify-send "🔊 Audio Switch" "Audio Switch to HDMI Stereo"
fi
